# version format
version: 2.3.0.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

cache:
- C:\projects\merchello-plugin-payment-braintree\src\packages -> appveyor.yml


build_script:
- build-appveyor.cmd

test:
   assemblies:
      - '..\tests\Merchello.Tests.Braintree.IntegrationTests\bin\Release\Merchello.Tests.Braintree.Integration.dll'

# run custom scripts before tests
before_test:

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
  # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/merchello/api/v2/
    symbol_server: https://www.myget.org/F/merchello/api/v2/package
    api_key:
      secure: 34B4mXhAYW6XOw8H9ZVh+KhbKKjXnb8QIp8bpoIKrkx5Uivcg0D4cRbu/pvdI65o
    artifact: /.*\.nupkg/
    on:
      branch: master